networks:
  tsc-network:
    driver: bridge
  nginx-proxy:
    external: true

volumes:
  app:

services:
  app:
    build:
      context: .
      dockerfile: ./docker-compose/app/Dockerfile
    image: tsc-prod
    container_name: tsc-app
    working_dir: /var/www
    volumes:
      - app:/var/www
    restart: always
    environment:
      APP_ENV: production
    networks:
      - tsc-network

  nginx:
    image: nginx:alpine
    container_name: tsc-nginx
    restart: always
    expose:
      - 80
    volumes:
      - app:/var/www:ro
      - ./docker-compose/nginx:/etc/nginx/conf.d
    environment:
      VIRTUAL_HOST: api.thesatoshicircle.it
      LETSENCRYPT_HOST: api.thesatoshicircle.it
      LETSENCRYPT_EMAIL: hello@thebatclaud.io
    networks:
      - tsc-network
      - nginx-proxy
